// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"healthmonitor/ent/adminpermission"
	"healthmonitor/ent/adminrolepermission"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AdminPermissionCreate is the builder for creating a AdminPermission entity.
type AdminPermissionCreate struct {
	config
	mutation *AdminPermissionMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (apc *AdminPermissionCreate) SetName(s string) *AdminPermissionCreate {
	apc.mutation.SetName(s)
	return apc
}

// SetDescription sets the "description" field.
func (apc *AdminPermissionCreate) SetDescription(s string) *AdminPermissionCreate {
	apc.mutation.SetDescription(s)
	return apc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (apc *AdminPermissionCreate) SetNillableDescription(s *string) *AdminPermissionCreate {
	if s != nil {
		apc.SetDescription(*s)
	}
	return apc
}

// SetPath sets the "path" field.
func (apc *AdminPermissionCreate) SetPath(s string) *AdminPermissionCreate {
	apc.mutation.SetPath(s)
	return apc
}

// SetMethod sets the "method" field.
func (apc *AdminPermissionCreate) SetMethod(s string) *AdminPermissionCreate {
	apc.mutation.SetMethod(s)
	return apc
}

// SetCreatedAt sets the "created_at" field.
func (apc *AdminPermissionCreate) SetCreatedAt(t time.Time) *AdminPermissionCreate {
	apc.mutation.SetCreatedAt(t)
	return apc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (apc *AdminPermissionCreate) SetNillableCreatedAt(t *time.Time) *AdminPermissionCreate {
	if t != nil {
		apc.SetCreatedAt(*t)
	}
	return apc
}

// SetUpdatedAt sets the "updated_at" field.
func (apc *AdminPermissionCreate) SetUpdatedAt(t time.Time) *AdminPermissionCreate {
	apc.mutation.SetUpdatedAt(t)
	return apc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (apc *AdminPermissionCreate) SetNillableUpdatedAt(t *time.Time) *AdminPermissionCreate {
	if t != nil {
		apc.SetUpdatedAt(*t)
	}
	return apc
}

// SetID sets the "id" field.
func (apc *AdminPermissionCreate) SetID(u uuid.UUID) *AdminPermissionCreate {
	apc.mutation.SetID(u)
	return apc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (apc *AdminPermissionCreate) SetNillableID(u *uuid.UUID) *AdminPermissionCreate {
	if u != nil {
		apc.SetID(*u)
	}
	return apc
}

// AddRoleIDs adds the "roles" edge to the AdminRolePermission entity by IDs.
func (apc *AdminPermissionCreate) AddRoleIDs(ids ...int) *AdminPermissionCreate {
	apc.mutation.AddRoleIDs(ids...)
	return apc
}

// AddRoles adds the "roles" edges to the AdminRolePermission entity.
func (apc *AdminPermissionCreate) AddRoles(a ...*AdminRolePermission) *AdminPermissionCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return apc.AddRoleIDs(ids...)
}

// Mutation returns the AdminPermissionMutation object of the builder.
func (apc *AdminPermissionCreate) Mutation() *AdminPermissionMutation {
	return apc.mutation
}

// Save creates the AdminPermission in the database.
func (apc *AdminPermissionCreate) Save(ctx context.Context) (*AdminPermission, error) {
	apc.defaults()
	return withHooks(ctx, apc.sqlSave, apc.mutation, apc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (apc *AdminPermissionCreate) SaveX(ctx context.Context) *AdminPermission {
	v, err := apc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (apc *AdminPermissionCreate) Exec(ctx context.Context) error {
	_, err := apc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apc *AdminPermissionCreate) ExecX(ctx context.Context) {
	if err := apc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (apc *AdminPermissionCreate) defaults() {
	if _, ok := apc.mutation.CreatedAt(); !ok {
		v := adminpermission.DefaultCreatedAt()
		apc.mutation.SetCreatedAt(v)
	}
	if _, ok := apc.mutation.UpdatedAt(); !ok {
		v := adminpermission.DefaultUpdatedAt()
		apc.mutation.SetUpdatedAt(v)
	}
	if _, ok := apc.mutation.ID(); !ok {
		v := adminpermission.DefaultID()
		apc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (apc *AdminPermissionCreate) check() error {
	if _, ok := apc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AdminPermission.name"`)}
	}
	if _, ok := apc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "AdminPermission.path"`)}
	}
	if _, ok := apc.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "AdminPermission.method"`)}
	}
	if _, ok := apc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminPermission.created_at"`)}
	}
	if _, ok := apc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AdminPermission.updated_at"`)}
	}
	return nil
}

func (apc *AdminPermissionCreate) sqlSave(ctx context.Context) (*AdminPermission, error) {
	if err := apc.check(); err != nil {
		return nil, err
	}
	_node, _spec := apc.createSpec()
	if err := sqlgraph.CreateNode(ctx, apc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	apc.mutation.id = &_node.ID
	apc.mutation.done = true
	return _node, nil
}

func (apc *AdminPermissionCreate) createSpec() (*AdminPermission, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminPermission{config: apc.config}
		_spec = sqlgraph.NewCreateSpec(adminpermission.Table, sqlgraph.NewFieldSpec(adminpermission.FieldID, field.TypeUUID))
	)
	if id, ok := apc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := apc.mutation.Name(); ok {
		_spec.SetField(adminpermission.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := apc.mutation.Description(); ok {
		_spec.SetField(adminpermission.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := apc.mutation.Path(); ok {
		_spec.SetField(adminpermission.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := apc.mutation.Method(); ok {
		_spec.SetField(adminpermission.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := apc.mutation.CreatedAt(); ok {
		_spec.SetField(adminpermission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := apc.mutation.UpdatedAt(); ok {
		_spec.SetField(adminpermission.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := apc.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adminpermission.RolesTable,
			Columns: []string{adminpermission.RolesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(adminrolepermission.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AdminPermissionCreateBulk is the builder for creating many AdminPermission entities in bulk.
type AdminPermissionCreateBulk struct {
	config
	err      error
	builders []*AdminPermissionCreate
}

// Save creates the AdminPermission entities in the database.
func (apcb *AdminPermissionCreateBulk) Save(ctx context.Context) ([]*AdminPermission, error) {
	if apcb.err != nil {
		return nil, apcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(apcb.builders))
	nodes := make([]*AdminPermission, len(apcb.builders))
	mutators := make([]Mutator, len(apcb.builders))
	for i := range apcb.builders {
		func(i int, root context.Context) {
			builder := apcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminPermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, apcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, apcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, apcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (apcb *AdminPermissionCreateBulk) SaveX(ctx context.Context) []*AdminPermission {
	v, err := apcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (apcb *AdminPermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := apcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (apcb *AdminPermissionCreateBulk) ExecX(ctx context.Context) {
	if err := apcb.Exec(ctx); err != nil {
		panic(err)
	}
}
