// Code generated by ent, DO NOT EDIT.

package ent

import (
	"HealthMonitor/ent/adminrolepermission"
	"HealthMonitor/ent/adminroles"
	"HealthMonitor/ent/adminuserrole"
	"HealthMonitor/ent/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AdminRolesQuery is the builder for querying AdminRoles entities.
type AdminRolesQuery struct {
	config
	ctx             *QueryContext
	order           []adminroles.OrderOption
	inters          []Interceptor
	predicates      []predicate.AdminRoles
	withPermissions *AdminRolePermissionQuery
	withUsers       *AdminUserRoleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdminRolesQuery builder.
func (arq *AdminRolesQuery) Where(ps ...predicate.AdminRoles) *AdminRolesQuery {
	arq.predicates = append(arq.predicates, ps...)
	return arq
}

// Limit the number of records to be returned by this query.
func (arq *AdminRolesQuery) Limit(limit int) *AdminRolesQuery {
	arq.ctx.Limit = &limit
	return arq
}

// Offset to start from.
func (arq *AdminRolesQuery) Offset(offset int) *AdminRolesQuery {
	arq.ctx.Offset = &offset
	return arq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (arq *AdminRolesQuery) Unique(unique bool) *AdminRolesQuery {
	arq.ctx.Unique = &unique
	return arq
}

// Order specifies how the records should be ordered.
func (arq *AdminRolesQuery) Order(o ...adminroles.OrderOption) *AdminRolesQuery {
	arq.order = append(arq.order, o...)
	return arq
}

// QueryPermissions chains the current query on the "permissions" edge.
func (arq *AdminRolesQuery) QueryPermissions() *AdminRolePermissionQuery {
	query := (&AdminRolePermissionClient{config: arq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := arq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := arq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminroles.Table, adminroles.FieldID, selector),
			sqlgraph.To(adminrolepermission.Table, adminrolepermission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, adminroles.PermissionsTable, adminroles.PermissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(arq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsers chains the current query on the "users" edge.
func (arq *AdminRolesQuery) QueryUsers() *AdminUserRoleQuery {
	query := (&AdminUserRoleClient{config: arq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := arq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := arq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminroles.Table, adminroles.FieldID, selector),
			sqlgraph.To(adminuserrole.Table, adminuserrole.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, adminroles.UsersTable, adminroles.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(arq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdminRoles entity from the query.
// Returns a *NotFoundError when no AdminRoles was found.
func (arq *AdminRolesQuery) First(ctx context.Context) (*AdminRoles, error) {
	nodes, err := arq.Limit(1).All(setContextOp(ctx, arq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adminroles.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (arq *AdminRolesQuery) FirstX(ctx context.Context) *AdminRoles {
	node, err := arq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdminRoles ID from the query.
// Returns a *NotFoundError when no AdminRoles ID was found.
func (arq *AdminRolesQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = arq.Limit(1).IDs(setContextOp(ctx, arq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adminroles.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (arq *AdminRolesQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := arq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdminRoles entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdminRoles entity is found.
// Returns a *NotFoundError when no AdminRoles entities are found.
func (arq *AdminRolesQuery) Only(ctx context.Context) (*AdminRoles, error) {
	nodes, err := arq.Limit(2).All(setContextOp(ctx, arq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adminroles.Label}
	default:
		return nil, &NotSingularError{adminroles.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (arq *AdminRolesQuery) OnlyX(ctx context.Context) *AdminRoles {
	node, err := arq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdminRoles ID in the query.
// Returns a *NotSingularError when more than one AdminRoles ID is found.
// Returns a *NotFoundError when no entities are found.
func (arq *AdminRolesQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = arq.Limit(2).IDs(setContextOp(ctx, arq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adminroles.Label}
	default:
		err = &NotSingularError{adminroles.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (arq *AdminRolesQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := arq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdminRolesSlice.
func (arq *AdminRolesQuery) All(ctx context.Context) ([]*AdminRoles, error) {
	ctx = setContextOp(ctx, arq.ctx, ent.OpQueryAll)
	if err := arq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdminRoles, *AdminRolesQuery]()
	return withInterceptors[[]*AdminRoles](ctx, arq, qr, arq.inters)
}

// AllX is like All, but panics if an error occurs.
func (arq *AdminRolesQuery) AllX(ctx context.Context) []*AdminRoles {
	nodes, err := arq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdminRoles IDs.
func (arq *AdminRolesQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if arq.ctx.Unique == nil && arq.path != nil {
		arq.Unique(true)
	}
	ctx = setContextOp(ctx, arq.ctx, ent.OpQueryIDs)
	if err = arq.Select(adminroles.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (arq *AdminRolesQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := arq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (arq *AdminRolesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, arq.ctx, ent.OpQueryCount)
	if err := arq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, arq, querierCount[*AdminRolesQuery](), arq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (arq *AdminRolesQuery) CountX(ctx context.Context) int {
	count, err := arq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (arq *AdminRolesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, arq.ctx, ent.OpQueryExist)
	switch _, err := arq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (arq *AdminRolesQuery) ExistX(ctx context.Context) bool {
	exist, err := arq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdminRolesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (arq *AdminRolesQuery) Clone() *AdminRolesQuery {
	if arq == nil {
		return nil
	}
	return &AdminRolesQuery{
		config:          arq.config,
		ctx:             arq.ctx.Clone(),
		order:           append([]adminroles.OrderOption{}, arq.order...),
		inters:          append([]Interceptor{}, arq.inters...),
		predicates:      append([]predicate.AdminRoles{}, arq.predicates...),
		withPermissions: arq.withPermissions.Clone(),
		withUsers:       arq.withUsers.Clone(),
		// clone intermediate query.
		sql:  arq.sql.Clone(),
		path: arq.path,
	}
}

// WithPermissions tells the query-builder to eager-load the nodes that are connected to
// the "permissions" edge. The optional arguments are used to configure the query builder of the edge.
func (arq *AdminRolesQuery) WithPermissions(opts ...func(*AdminRolePermissionQuery)) *AdminRolesQuery {
	query := (&AdminRolePermissionClient{config: arq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	arq.withPermissions = query
	return arq
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "users" edge. The optional arguments are used to configure the query builder of the edge.
func (arq *AdminRolesQuery) WithUsers(opts ...func(*AdminUserRoleQuery)) *AdminRolesQuery {
	query := (&AdminUserRoleClient{config: arq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	arq.withUsers = query
	return arq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdminRoles.Query().
//		GroupBy(adminroles.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (arq *AdminRolesQuery) GroupBy(field string, fields ...string) *AdminRolesGroupBy {
	arq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdminRolesGroupBy{build: arq}
	grbuild.flds = &arq.ctx.Fields
	grbuild.label = adminroles.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AdminRoles.Query().
//		Select(adminroles.FieldName).
//		Scan(ctx, &v)
func (arq *AdminRolesQuery) Select(fields ...string) *AdminRolesSelect {
	arq.ctx.Fields = append(arq.ctx.Fields, fields...)
	sbuild := &AdminRolesSelect{AdminRolesQuery: arq}
	sbuild.label = adminroles.Label
	sbuild.flds, sbuild.scan = &arq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdminRolesSelect configured with the given aggregations.
func (arq *AdminRolesQuery) Aggregate(fns ...AggregateFunc) *AdminRolesSelect {
	return arq.Select().Aggregate(fns...)
}

func (arq *AdminRolesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range arq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, arq); err != nil {
				return err
			}
		}
	}
	for _, f := range arq.ctx.Fields {
		if !adminroles.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if arq.path != nil {
		prev, err := arq.path(ctx)
		if err != nil {
			return err
		}
		arq.sql = prev
	}
	return nil
}

func (arq *AdminRolesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdminRoles, error) {
	var (
		nodes       = []*AdminRoles{}
		_spec       = arq.querySpec()
		loadedTypes = [2]bool{
			arq.withPermissions != nil,
			arq.withUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdminRoles).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdminRoles{config: arq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, arq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := arq.withPermissions; query != nil {
		if err := arq.loadPermissions(ctx, query, nodes,
			func(n *AdminRoles) { n.Edges.Permissions = []*AdminRolePermission{} },
			func(n *AdminRoles, e *AdminRolePermission) { n.Edges.Permissions = append(n.Edges.Permissions, e) }); err != nil {
			return nil, err
		}
	}
	if query := arq.withUsers; query != nil {
		if err := arq.loadUsers(ctx, query, nodes,
			func(n *AdminRoles) { n.Edges.Users = []*AdminUserRole{} },
			func(n *AdminRoles, e *AdminUserRole) { n.Edges.Users = append(n.Edges.Users, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (arq *AdminRolesQuery) loadPermissions(ctx context.Context, query *AdminRolePermissionQuery, nodes []*AdminRoles, init func(*AdminRoles), assign func(*AdminRoles, *AdminRolePermission)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AdminRoles)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AdminRolePermission(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(adminroles.PermissionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.admin_roles_permissions
		if fk == nil {
			return fmt.Errorf(`foreign-key "admin_roles_permissions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "admin_roles_permissions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (arq *AdminRolesQuery) loadUsers(ctx context.Context, query *AdminUserRoleQuery, nodes []*AdminRoles, init func(*AdminRoles), assign func(*AdminRoles, *AdminUserRole)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AdminRoles)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AdminUserRole(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(adminroles.UsersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.admin_roles_users
		if fk == nil {
			return fmt.Errorf(`foreign-key "admin_roles_users" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "admin_roles_users" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (arq *AdminRolesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := arq.querySpec()
	_spec.Node.Columns = arq.ctx.Fields
	if len(arq.ctx.Fields) > 0 {
		_spec.Unique = arq.ctx.Unique != nil && *arq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, arq.driver, _spec)
}

func (arq *AdminRolesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adminroles.Table, adminroles.Columns, sqlgraph.NewFieldSpec(adminroles.FieldID, field.TypeUUID))
	_spec.From = arq.sql
	if unique := arq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if arq.path != nil {
		_spec.Unique = true
	}
	if fields := arq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminroles.FieldID)
		for i := range fields {
			if fields[i] != adminroles.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := arq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := arq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := arq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := arq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (arq *AdminRolesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(arq.driver.Dialect())
	t1 := builder.Table(adminroles.Table)
	columns := arq.ctx.Fields
	if len(columns) == 0 {
		columns = adminroles.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if arq.sql != nil {
		selector = arq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if arq.ctx.Unique != nil && *arq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range arq.predicates {
		p(selector)
	}
	for _, p := range arq.order {
		p(selector)
	}
	if offset := arq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := arq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdminRolesGroupBy is the group-by builder for AdminRoles entities.
type AdminRolesGroupBy struct {
	selector
	build *AdminRolesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (argb *AdminRolesGroupBy) Aggregate(fns ...AggregateFunc) *AdminRolesGroupBy {
	argb.fns = append(argb.fns, fns...)
	return argb
}

// Scan applies the selector query and scans the result into the given value.
func (argb *AdminRolesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, argb.build.ctx, ent.OpQueryGroupBy)
	if err := argb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminRolesQuery, *AdminRolesGroupBy](ctx, argb.build, argb, argb.build.inters, v)
}

func (argb *AdminRolesGroupBy) sqlScan(ctx context.Context, root *AdminRolesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(argb.fns))
	for _, fn := range argb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*argb.flds)+len(argb.fns))
		for _, f := range *argb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*argb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := argb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdminRolesSelect is the builder for selecting fields of AdminRoles entities.
type AdminRolesSelect struct {
	*AdminRolesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ars *AdminRolesSelect) Aggregate(fns ...AggregateFunc) *AdminRolesSelect {
	ars.fns = append(ars.fns, fns...)
	return ars
}

// Scan applies the selector query and scans the result into the given value.
func (ars *AdminRolesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ars.ctx, ent.OpQuerySelect)
	if err := ars.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminRolesQuery, *AdminRolesSelect](ctx, ars.AdminRolesQuery, ars, ars.inters, v)
}

func (ars *AdminRolesSelect) sqlScan(ctx context.Context, root *AdminRolesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ars.fns))
	for _, fn := range ars.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ars.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ars.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
