// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"healthmonitor/ent/adminlog"
	"healthmonitor/ent/adminuser"
	"healthmonitor/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AdminLogQuery is the builder for querying AdminLog entities.
type AdminLogQuery struct {
	config
	ctx        *QueryContext
	order      []adminlog.OrderOption
	inters     []Interceptor
	predicates []predicate.AdminLog
	withUser   *AdminUserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdminLogQuery builder.
func (alq *AdminLogQuery) Where(ps ...predicate.AdminLog) *AdminLogQuery {
	alq.predicates = append(alq.predicates, ps...)
	return alq
}

// Limit the number of records to be returned by this query.
func (alq *AdminLogQuery) Limit(limit int) *AdminLogQuery {
	alq.ctx.Limit = &limit
	return alq
}

// Offset to start from.
func (alq *AdminLogQuery) Offset(offset int) *AdminLogQuery {
	alq.ctx.Offset = &offset
	return alq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (alq *AdminLogQuery) Unique(unique bool) *AdminLogQuery {
	alq.ctx.Unique = &unique
	return alq
}

// Order specifies how the records should be ordered.
func (alq *AdminLogQuery) Order(o ...adminlog.OrderOption) *AdminLogQuery {
	alq.order = append(alq.order, o...)
	return alq
}

// QueryUser chains the current query on the "user" edge.
func (alq *AdminLogQuery) QueryUser() *AdminUserQuery {
	query := (&AdminUserClient{config: alq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := alq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := alq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminlog.Table, adminlog.FieldID, selector),
			sqlgraph.To(adminuser.Table, adminuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adminlog.UserTable, adminlog.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(alq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdminLog entity from the query.
// Returns a *NotFoundError when no AdminLog was found.
func (alq *AdminLogQuery) First(ctx context.Context) (*AdminLog, error) {
	nodes, err := alq.Limit(1).All(setContextOp(ctx, alq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adminlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (alq *AdminLogQuery) FirstX(ctx context.Context) *AdminLog {
	node, err := alq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdminLog ID from the query.
// Returns a *NotFoundError when no AdminLog ID was found.
func (alq *AdminLogQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = alq.Limit(1).IDs(setContextOp(ctx, alq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adminlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (alq *AdminLogQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := alq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdminLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdminLog entity is found.
// Returns a *NotFoundError when no AdminLog entities are found.
func (alq *AdminLogQuery) Only(ctx context.Context) (*AdminLog, error) {
	nodes, err := alq.Limit(2).All(setContextOp(ctx, alq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adminlog.Label}
	default:
		return nil, &NotSingularError{adminlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (alq *AdminLogQuery) OnlyX(ctx context.Context) *AdminLog {
	node, err := alq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdminLog ID in the query.
// Returns a *NotSingularError when more than one AdminLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (alq *AdminLogQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = alq.Limit(2).IDs(setContextOp(ctx, alq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adminlog.Label}
	default:
		err = &NotSingularError{adminlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (alq *AdminLogQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := alq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdminLogs.
func (alq *AdminLogQuery) All(ctx context.Context) ([]*AdminLog, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryAll)
	if err := alq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdminLog, *AdminLogQuery]()
	return withInterceptors[[]*AdminLog](ctx, alq, qr, alq.inters)
}

// AllX is like All, but panics if an error occurs.
func (alq *AdminLogQuery) AllX(ctx context.Context) []*AdminLog {
	nodes, err := alq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdminLog IDs.
func (alq *AdminLogQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if alq.ctx.Unique == nil && alq.path != nil {
		alq.Unique(true)
	}
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryIDs)
	if err = alq.Select(adminlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (alq *AdminLogQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := alq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (alq *AdminLogQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryCount)
	if err := alq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, alq, querierCount[*AdminLogQuery](), alq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (alq *AdminLogQuery) CountX(ctx context.Context) int {
	count, err := alq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (alq *AdminLogQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, alq.ctx, ent.OpQueryExist)
	switch _, err := alq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (alq *AdminLogQuery) ExistX(ctx context.Context) bool {
	exist, err := alq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdminLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (alq *AdminLogQuery) Clone() *AdminLogQuery {
	if alq == nil {
		return nil
	}
	return &AdminLogQuery{
		config:     alq.config,
		ctx:        alq.ctx.Clone(),
		order:      append([]adminlog.OrderOption{}, alq.order...),
		inters:     append([]Interceptor{}, alq.inters...),
		predicates: append([]predicate.AdminLog{}, alq.predicates...),
		withUser:   alq.withUser.Clone(),
		// clone intermediate query.
		sql:  alq.sql.Clone(),
		path: alq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (alq *AdminLogQuery) WithUser(opts ...func(*AdminUserQuery)) *AdminLogQuery {
	query := (&AdminUserClient{config: alq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	alq.withUser = query
	return alq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Action string `json:"action,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdminLog.Query().
//		GroupBy(adminlog.FieldAction).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (alq *AdminLogQuery) GroupBy(field string, fields ...string) *AdminLogGroupBy {
	alq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdminLogGroupBy{build: alq}
	grbuild.flds = &alq.ctx.Fields
	grbuild.label = adminlog.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Action string `json:"action,omitempty"`
//	}
//
//	client.AdminLog.Query().
//		Select(adminlog.FieldAction).
//		Scan(ctx, &v)
func (alq *AdminLogQuery) Select(fields ...string) *AdminLogSelect {
	alq.ctx.Fields = append(alq.ctx.Fields, fields...)
	sbuild := &AdminLogSelect{AdminLogQuery: alq}
	sbuild.label = adminlog.Label
	sbuild.flds, sbuild.scan = &alq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdminLogSelect configured with the given aggregations.
func (alq *AdminLogQuery) Aggregate(fns ...AggregateFunc) *AdminLogSelect {
	return alq.Select().Aggregate(fns...)
}

func (alq *AdminLogQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range alq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, alq); err != nil {
				return err
			}
		}
	}
	for _, f := range alq.ctx.Fields {
		if !adminlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if alq.path != nil {
		prev, err := alq.path(ctx)
		if err != nil {
			return err
		}
		alq.sql = prev
	}
	return nil
}

func (alq *AdminLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdminLog, error) {
	var (
		nodes       = []*AdminLog{}
		withFKs     = alq.withFKs
		_spec       = alq.querySpec()
		loadedTypes = [1]bool{
			alq.withUser != nil,
		}
	)
	if alq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, adminlog.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdminLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdminLog{config: alq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, alq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := alq.withUser; query != nil {
		if err := alq.loadUser(ctx, query, nodes, nil,
			func(n *AdminLog, e *AdminUser) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (alq *AdminLogQuery) loadUser(ctx context.Context, query *AdminUserQuery, nodes []*AdminLog, init func(*AdminLog), assign func(*AdminLog, *AdminUser)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AdminLog)
	for i := range nodes {
		if nodes[i].admin_user_logs == nil {
			continue
		}
		fk := *nodes[i].admin_user_logs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "admin_user_logs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (alq *AdminLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := alq.querySpec()
	_spec.Node.Columns = alq.ctx.Fields
	if len(alq.ctx.Fields) > 0 {
		_spec.Unique = alq.ctx.Unique != nil && *alq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, alq.driver, _spec)
}

func (alq *AdminLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adminlog.Table, adminlog.Columns, sqlgraph.NewFieldSpec(adminlog.FieldID, field.TypeUUID))
	_spec.From = alq.sql
	if unique := alq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if alq.path != nil {
		_spec.Unique = true
	}
	if fields := alq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminlog.FieldID)
		for i := range fields {
			if fields[i] != adminlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := alq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := alq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := alq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := alq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (alq *AdminLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(alq.driver.Dialect())
	t1 := builder.Table(adminlog.Table)
	columns := alq.ctx.Fields
	if len(columns) == 0 {
		columns = adminlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if alq.sql != nil {
		selector = alq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if alq.ctx.Unique != nil && *alq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range alq.predicates {
		p(selector)
	}
	for _, p := range alq.order {
		p(selector)
	}
	if offset := alq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := alq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdminLogGroupBy is the group-by builder for AdminLog entities.
type AdminLogGroupBy struct {
	selector
	build *AdminLogQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (algb *AdminLogGroupBy) Aggregate(fns ...AggregateFunc) *AdminLogGroupBy {
	algb.fns = append(algb.fns, fns...)
	return algb
}

// Scan applies the selector query and scans the result into the given value.
func (algb *AdminLogGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, algb.build.ctx, ent.OpQueryGroupBy)
	if err := algb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminLogQuery, *AdminLogGroupBy](ctx, algb.build, algb, algb.build.inters, v)
}

func (algb *AdminLogGroupBy) sqlScan(ctx context.Context, root *AdminLogQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(algb.fns))
	for _, fn := range algb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*algb.flds)+len(algb.fns))
		for _, f := range *algb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*algb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := algb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdminLogSelect is the builder for selecting fields of AdminLog entities.
type AdminLogSelect struct {
	*AdminLogQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (als *AdminLogSelect) Aggregate(fns ...AggregateFunc) *AdminLogSelect {
	als.fns = append(als.fns, fns...)
	return als
}

// Scan applies the selector query and scans the result into the given value.
func (als *AdminLogSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, als.ctx, ent.OpQuerySelect)
	if err := als.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminLogQuery, *AdminLogSelect](ctx, als.AdminLogQuery, als, als.inters, v)
}

func (als *AdminLogSelect) sqlScan(ctx context.Context, root *AdminLogQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(als.fns))
	for _, fn := range als.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*als.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := als.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
