// Code generated by ent, DO NOT EDIT.

package ent

import (
	"HealthMonitor/ent/adminroles"
	"HealthMonitor/ent/adminuser"
	"HealthMonitor/ent/adminuserrole"
	"HealthMonitor/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AdminUserRoleQuery is the builder for querying AdminUserRole entities.
type AdminUserRoleQuery struct {
	config
	ctx        *QueryContext
	order      []adminuserrole.OrderOption
	inters     []Interceptor
	predicates []predicate.AdminUserRole
	withUser   *AdminUserQuery
	withRole   *AdminRolesQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdminUserRoleQuery builder.
func (aurq *AdminUserRoleQuery) Where(ps ...predicate.AdminUserRole) *AdminUserRoleQuery {
	aurq.predicates = append(aurq.predicates, ps...)
	return aurq
}

// Limit the number of records to be returned by this query.
func (aurq *AdminUserRoleQuery) Limit(limit int) *AdminUserRoleQuery {
	aurq.ctx.Limit = &limit
	return aurq
}

// Offset to start from.
func (aurq *AdminUserRoleQuery) Offset(offset int) *AdminUserRoleQuery {
	aurq.ctx.Offset = &offset
	return aurq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aurq *AdminUserRoleQuery) Unique(unique bool) *AdminUserRoleQuery {
	aurq.ctx.Unique = &unique
	return aurq
}

// Order specifies how the records should be ordered.
func (aurq *AdminUserRoleQuery) Order(o ...adminuserrole.OrderOption) *AdminUserRoleQuery {
	aurq.order = append(aurq.order, o...)
	return aurq
}

// QueryUser chains the current query on the "user" edge.
func (aurq *AdminUserRoleQuery) QueryUser() *AdminUserQuery {
	query := (&AdminUserClient{config: aurq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aurq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aurq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminuserrole.Table, adminuserrole.FieldID, selector),
			sqlgraph.To(adminuser.Table, adminuser.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adminuserrole.UserTable, adminuserrole.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(aurq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRole chains the current query on the "role" edge.
func (aurq *AdminUserRoleQuery) QueryRole() *AdminRolesQuery {
	query := (&AdminRolesClient{config: aurq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aurq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aurq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminuserrole.Table, adminuserrole.FieldID, selector),
			sqlgraph.To(adminroles.Table, adminroles.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adminuserrole.RoleTable, adminuserrole.RoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(aurq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdminUserRole entity from the query.
// Returns a *NotFoundError when no AdminUserRole was found.
func (aurq *AdminUserRoleQuery) First(ctx context.Context) (*AdminUserRole, error) {
	nodes, err := aurq.Limit(1).All(setContextOp(ctx, aurq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adminuserrole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aurq *AdminUserRoleQuery) FirstX(ctx context.Context) *AdminUserRole {
	node, err := aurq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdminUserRole ID from the query.
// Returns a *NotFoundError when no AdminUserRole ID was found.
func (aurq *AdminUserRoleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aurq.Limit(1).IDs(setContextOp(ctx, aurq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adminuserrole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aurq *AdminUserRoleQuery) FirstIDX(ctx context.Context) int {
	id, err := aurq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdminUserRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdminUserRole entity is found.
// Returns a *NotFoundError when no AdminUserRole entities are found.
func (aurq *AdminUserRoleQuery) Only(ctx context.Context) (*AdminUserRole, error) {
	nodes, err := aurq.Limit(2).All(setContextOp(ctx, aurq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adminuserrole.Label}
	default:
		return nil, &NotSingularError{adminuserrole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aurq *AdminUserRoleQuery) OnlyX(ctx context.Context) *AdminUserRole {
	node, err := aurq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdminUserRole ID in the query.
// Returns a *NotSingularError when more than one AdminUserRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (aurq *AdminUserRoleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aurq.Limit(2).IDs(setContextOp(ctx, aurq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adminuserrole.Label}
	default:
		err = &NotSingularError{adminuserrole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aurq *AdminUserRoleQuery) OnlyIDX(ctx context.Context) int {
	id, err := aurq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdminUserRoles.
func (aurq *AdminUserRoleQuery) All(ctx context.Context) ([]*AdminUserRole, error) {
	ctx = setContextOp(ctx, aurq.ctx, ent.OpQueryAll)
	if err := aurq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdminUserRole, *AdminUserRoleQuery]()
	return withInterceptors[[]*AdminUserRole](ctx, aurq, qr, aurq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aurq *AdminUserRoleQuery) AllX(ctx context.Context) []*AdminUserRole {
	nodes, err := aurq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdminUserRole IDs.
func (aurq *AdminUserRoleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if aurq.ctx.Unique == nil && aurq.path != nil {
		aurq.Unique(true)
	}
	ctx = setContextOp(ctx, aurq.ctx, ent.OpQueryIDs)
	if err = aurq.Select(adminuserrole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aurq *AdminUserRoleQuery) IDsX(ctx context.Context) []int {
	ids, err := aurq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aurq *AdminUserRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aurq.ctx, ent.OpQueryCount)
	if err := aurq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aurq, querierCount[*AdminUserRoleQuery](), aurq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aurq *AdminUserRoleQuery) CountX(ctx context.Context) int {
	count, err := aurq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aurq *AdminUserRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aurq.ctx, ent.OpQueryExist)
	switch _, err := aurq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aurq *AdminUserRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := aurq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdminUserRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aurq *AdminUserRoleQuery) Clone() *AdminUserRoleQuery {
	if aurq == nil {
		return nil
	}
	return &AdminUserRoleQuery{
		config:     aurq.config,
		ctx:        aurq.ctx.Clone(),
		order:      append([]adminuserrole.OrderOption{}, aurq.order...),
		inters:     append([]Interceptor{}, aurq.inters...),
		predicates: append([]predicate.AdminUserRole{}, aurq.predicates...),
		withUser:   aurq.withUser.Clone(),
		withRole:   aurq.withRole.Clone(),
		// clone intermediate query.
		sql:  aurq.sql.Clone(),
		path: aurq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (aurq *AdminUserRoleQuery) WithUser(opts ...func(*AdminUserQuery)) *AdminUserRoleQuery {
	query := (&AdminUserClient{config: aurq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aurq.withUser = query
	return aurq
}

// WithRole tells the query-builder to eager-load the nodes that are connected to
// the "role" edge. The optional arguments are used to configure the query builder of the edge.
func (aurq *AdminUserRoleQuery) WithRole(opts ...func(*AdminRolesQuery)) *AdminUserRoleQuery {
	query := (&AdminRolesClient{config: aurq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aurq.withRole = query
	return aurq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (aurq *AdminUserRoleQuery) GroupBy(field string, fields ...string) *AdminUserRoleGroupBy {
	aurq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdminUserRoleGroupBy{build: aurq}
	grbuild.flds = &aurq.ctx.Fields
	grbuild.label = adminuserrole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (aurq *AdminUserRoleQuery) Select(fields ...string) *AdminUserRoleSelect {
	aurq.ctx.Fields = append(aurq.ctx.Fields, fields...)
	sbuild := &AdminUserRoleSelect{AdminUserRoleQuery: aurq}
	sbuild.label = adminuserrole.Label
	sbuild.flds, sbuild.scan = &aurq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdminUserRoleSelect configured with the given aggregations.
func (aurq *AdminUserRoleQuery) Aggregate(fns ...AggregateFunc) *AdminUserRoleSelect {
	return aurq.Select().Aggregate(fns...)
}

func (aurq *AdminUserRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aurq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aurq); err != nil {
				return err
			}
		}
	}
	for _, f := range aurq.ctx.Fields {
		if !adminuserrole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aurq.path != nil {
		prev, err := aurq.path(ctx)
		if err != nil {
			return err
		}
		aurq.sql = prev
	}
	return nil
}

func (aurq *AdminUserRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdminUserRole, error) {
	var (
		nodes       = []*AdminUserRole{}
		withFKs     = aurq.withFKs
		_spec       = aurq.querySpec()
		loadedTypes = [2]bool{
			aurq.withUser != nil,
			aurq.withRole != nil,
		}
	)
	if aurq.withUser != nil || aurq.withRole != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, adminuserrole.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdminUserRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdminUserRole{config: aurq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aurq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aurq.withUser; query != nil {
		if err := aurq.loadUser(ctx, query, nodes, nil,
			func(n *AdminUserRole, e *AdminUser) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := aurq.withRole; query != nil {
		if err := aurq.loadRole(ctx, query, nodes, nil,
			func(n *AdminUserRole, e *AdminRoles) { n.Edges.Role = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aurq *AdminUserRoleQuery) loadUser(ctx context.Context, query *AdminUserQuery, nodes []*AdminUserRole, init func(*AdminUserRole), assign func(*AdminUserRole, *AdminUser)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AdminUserRole)
	for i := range nodes {
		if nodes[i].admin_user_roles == nil {
			continue
		}
		fk := *nodes[i].admin_user_roles
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminuser.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "admin_user_roles" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (aurq *AdminUserRoleQuery) loadRole(ctx context.Context, query *AdminRolesQuery, nodes []*AdminUserRole, init func(*AdminUserRole), assign func(*AdminUserRole, *AdminRoles)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AdminUserRole)
	for i := range nodes {
		if nodes[i].admin_roles_users == nil {
			continue
		}
		fk := *nodes[i].admin_roles_users
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(adminroles.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "admin_roles_users" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (aurq *AdminUserRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aurq.querySpec()
	_spec.Node.Columns = aurq.ctx.Fields
	if len(aurq.ctx.Fields) > 0 {
		_spec.Unique = aurq.ctx.Unique != nil && *aurq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aurq.driver, _spec)
}

func (aurq *AdminUserRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adminuserrole.Table, adminuserrole.Columns, sqlgraph.NewFieldSpec(adminuserrole.FieldID, field.TypeInt))
	_spec.From = aurq.sql
	if unique := aurq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aurq.path != nil {
		_spec.Unique = true
	}
	if fields := aurq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminuserrole.FieldID)
		for i := range fields {
			if fields[i] != adminuserrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aurq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aurq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aurq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aurq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aurq *AdminUserRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aurq.driver.Dialect())
	t1 := builder.Table(adminuserrole.Table)
	columns := aurq.ctx.Fields
	if len(columns) == 0 {
		columns = adminuserrole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aurq.sql != nil {
		selector = aurq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aurq.ctx.Unique != nil && *aurq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aurq.predicates {
		p(selector)
	}
	for _, p := range aurq.order {
		p(selector)
	}
	if offset := aurq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aurq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdminUserRoleGroupBy is the group-by builder for AdminUserRole entities.
type AdminUserRoleGroupBy struct {
	selector
	build *AdminUserRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aurgb *AdminUserRoleGroupBy) Aggregate(fns ...AggregateFunc) *AdminUserRoleGroupBy {
	aurgb.fns = append(aurgb.fns, fns...)
	return aurgb
}

// Scan applies the selector query and scans the result into the given value.
func (aurgb *AdminUserRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aurgb.build.ctx, ent.OpQueryGroupBy)
	if err := aurgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminUserRoleQuery, *AdminUserRoleGroupBy](ctx, aurgb.build, aurgb, aurgb.build.inters, v)
}

func (aurgb *AdminUserRoleGroupBy) sqlScan(ctx context.Context, root *AdminUserRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aurgb.fns))
	for _, fn := range aurgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aurgb.flds)+len(aurgb.fns))
		for _, f := range *aurgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aurgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aurgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdminUserRoleSelect is the builder for selecting fields of AdminUserRole entities.
type AdminUserRoleSelect struct {
	*AdminUserRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aurs *AdminUserRoleSelect) Aggregate(fns ...AggregateFunc) *AdminUserRoleSelect {
	aurs.fns = append(aurs.fns, fns...)
	return aurs
}

// Scan applies the selector query and scans the result into the given value.
func (aurs *AdminUserRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aurs.ctx, ent.OpQuerySelect)
	if err := aurs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminUserRoleQuery, *AdminUserRoleSelect](ctx, aurs.AdminUserRoleQuery, aurs, aurs.inters, v)
}

func (aurs *AdminUserRoleSelect) sqlScan(ctx context.Context, root *AdminUserRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aurs.fns))
	for _, fn := range aurs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aurs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aurs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
