// Code generated by ent, DO NOT EDIT.

package ent

import (
	"HealthMonitor/ent/adminlog"
	"HealthMonitor/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminLogDelete is the builder for deleting a AdminLog entity.
type AdminLogDelete struct {
	config
	hooks    []Hook
	mutation *AdminLogMutation
}

// Where appends a list predicates to the AdminLogDelete builder.
func (ald *AdminLogDelete) Where(ps ...predicate.AdminLog) *AdminLogDelete {
	ald.mutation.Where(ps...)
	return ald
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ald *AdminLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ald.sqlExec, ald.mutation, ald.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ald *AdminLogDelete) ExecX(ctx context.Context) int {
	n, err := ald.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ald *AdminLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(adminlog.Table, sqlgraph.NewFieldSpec(adminlog.FieldID, field.TypeUUID))
	if ps := ald.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ald.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ald.mutation.done = true
	return affected, err
}

// AdminLogDeleteOne is the builder for deleting a single AdminLog entity.
type AdminLogDeleteOne struct {
	ald *AdminLogDelete
}

// Where appends a list predicates to the AdminLogDelete builder.
func (aldo *AdminLogDeleteOne) Where(ps ...predicate.AdminLog) *AdminLogDeleteOne {
	aldo.ald.mutation.Where(ps...)
	return aldo
}

// Exec executes the deletion query.
func (aldo *AdminLogDeleteOne) Exec(ctx context.Context) error {
	n, err := aldo.ald.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adminlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aldo *AdminLogDeleteOne) ExecX(ctx context.Context) {
	if err := aldo.Exec(ctx); err != nil {
		panic(err)
	}
}
