// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"healthmonitor/ent/bloodstatusrecord"
	"healthmonitor/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// BloodStatusRecordQuery is the builder for querying BloodStatusRecord entities.
type BloodStatusRecordQuery struct {
	config
	ctx        *QueryContext
	order      []bloodstatusrecord.OrderOption
	inters     []Interceptor
	predicates []predicate.BloodStatusRecord
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BloodStatusRecordQuery builder.
func (bsrq *BloodStatusRecordQuery) Where(ps ...predicate.BloodStatusRecord) *BloodStatusRecordQuery {
	bsrq.predicates = append(bsrq.predicates, ps...)
	return bsrq
}

// Limit the number of records to be returned by this query.
func (bsrq *BloodStatusRecordQuery) Limit(limit int) *BloodStatusRecordQuery {
	bsrq.ctx.Limit = &limit
	return bsrq
}

// Offset to start from.
func (bsrq *BloodStatusRecordQuery) Offset(offset int) *BloodStatusRecordQuery {
	bsrq.ctx.Offset = &offset
	return bsrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bsrq *BloodStatusRecordQuery) Unique(unique bool) *BloodStatusRecordQuery {
	bsrq.ctx.Unique = &unique
	return bsrq
}

// Order specifies how the records should be ordered.
func (bsrq *BloodStatusRecordQuery) Order(o ...bloodstatusrecord.OrderOption) *BloodStatusRecordQuery {
	bsrq.order = append(bsrq.order, o...)
	return bsrq
}

// First returns the first BloodStatusRecord entity from the query.
// Returns a *NotFoundError when no BloodStatusRecord was found.
func (bsrq *BloodStatusRecordQuery) First(ctx context.Context) (*BloodStatusRecord, error) {
	nodes, err := bsrq.Limit(1).All(setContextOp(ctx, bsrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{bloodstatusrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bsrq *BloodStatusRecordQuery) FirstX(ctx context.Context) *BloodStatusRecord {
	node, err := bsrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first BloodStatusRecord ID from the query.
// Returns a *NotFoundError when no BloodStatusRecord ID was found.
func (bsrq *BloodStatusRecordQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bsrq.Limit(1).IDs(setContextOp(ctx, bsrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{bloodstatusrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bsrq *BloodStatusRecordQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := bsrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single BloodStatusRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one BloodStatusRecord entity is found.
// Returns a *NotFoundError when no BloodStatusRecord entities are found.
func (bsrq *BloodStatusRecordQuery) Only(ctx context.Context) (*BloodStatusRecord, error) {
	nodes, err := bsrq.Limit(2).All(setContextOp(ctx, bsrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{bloodstatusrecord.Label}
	default:
		return nil, &NotSingularError{bloodstatusrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bsrq *BloodStatusRecordQuery) OnlyX(ctx context.Context) *BloodStatusRecord {
	node, err := bsrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only BloodStatusRecord ID in the query.
// Returns a *NotSingularError when more than one BloodStatusRecord ID is found.
// Returns a *NotFoundError when no entities are found.
func (bsrq *BloodStatusRecordQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = bsrq.Limit(2).IDs(setContextOp(ctx, bsrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{bloodstatusrecord.Label}
	default:
		err = &NotSingularError{bloodstatusrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bsrq *BloodStatusRecordQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := bsrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of BloodStatusRecords.
func (bsrq *BloodStatusRecordQuery) All(ctx context.Context) ([]*BloodStatusRecord, error) {
	ctx = setContextOp(ctx, bsrq.ctx, ent.OpQueryAll)
	if err := bsrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*BloodStatusRecord, *BloodStatusRecordQuery]()
	return withInterceptors[[]*BloodStatusRecord](ctx, bsrq, qr, bsrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bsrq *BloodStatusRecordQuery) AllX(ctx context.Context) []*BloodStatusRecord {
	nodes, err := bsrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of BloodStatusRecord IDs.
func (bsrq *BloodStatusRecordQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if bsrq.ctx.Unique == nil && bsrq.path != nil {
		bsrq.Unique(true)
	}
	ctx = setContextOp(ctx, bsrq.ctx, ent.OpQueryIDs)
	if err = bsrq.Select(bloodstatusrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bsrq *BloodStatusRecordQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := bsrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bsrq *BloodStatusRecordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bsrq.ctx, ent.OpQueryCount)
	if err := bsrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bsrq, querierCount[*BloodStatusRecordQuery](), bsrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bsrq *BloodStatusRecordQuery) CountX(ctx context.Context) int {
	count, err := bsrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bsrq *BloodStatusRecordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bsrq.ctx, ent.OpQueryExist)
	switch _, err := bsrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bsrq *BloodStatusRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := bsrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BloodStatusRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bsrq *BloodStatusRecordQuery) Clone() *BloodStatusRecordQuery {
	if bsrq == nil {
		return nil
	}
	return &BloodStatusRecordQuery{
		config:     bsrq.config,
		ctx:        bsrq.ctx.Clone(),
		order:      append([]bloodstatusrecord.OrderOption{}, bsrq.order...),
		inters:     append([]Interceptor{}, bsrq.inters...),
		predicates: append([]predicate.BloodStatusRecord{}, bsrq.predicates...),
		// clone intermediate query.
		sql:  bsrq.sql.Clone(),
		path: bsrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.BloodStatusRecord.Query().
//		GroupBy(bloodstatusrecord.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bsrq *BloodStatusRecordQuery) GroupBy(field string, fields ...string) *BloodStatusRecordGroupBy {
	bsrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BloodStatusRecordGroupBy{build: bsrq}
	grbuild.flds = &bsrq.ctx.Fields
	grbuild.label = bloodstatusrecord.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.BloodStatusRecord.Query().
//		Select(bloodstatusrecord.FieldUserID).
//		Scan(ctx, &v)
func (bsrq *BloodStatusRecordQuery) Select(fields ...string) *BloodStatusRecordSelect {
	bsrq.ctx.Fields = append(bsrq.ctx.Fields, fields...)
	sbuild := &BloodStatusRecordSelect{BloodStatusRecordQuery: bsrq}
	sbuild.label = bloodstatusrecord.Label
	sbuild.flds, sbuild.scan = &bsrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BloodStatusRecordSelect configured with the given aggregations.
func (bsrq *BloodStatusRecordQuery) Aggregate(fns ...AggregateFunc) *BloodStatusRecordSelect {
	return bsrq.Select().Aggregate(fns...)
}

func (bsrq *BloodStatusRecordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bsrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bsrq); err != nil {
				return err
			}
		}
	}
	for _, f := range bsrq.ctx.Fields {
		if !bloodstatusrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bsrq.path != nil {
		prev, err := bsrq.path(ctx)
		if err != nil {
			return err
		}
		bsrq.sql = prev
	}
	return nil
}

func (bsrq *BloodStatusRecordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*BloodStatusRecord, error) {
	var (
		nodes = []*BloodStatusRecord{}
		_spec = bsrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*BloodStatusRecord).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &BloodStatusRecord{config: bsrq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bsrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (bsrq *BloodStatusRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bsrq.querySpec()
	_spec.Node.Columns = bsrq.ctx.Fields
	if len(bsrq.ctx.Fields) > 0 {
		_spec.Unique = bsrq.ctx.Unique != nil && *bsrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bsrq.driver, _spec)
}

func (bsrq *BloodStatusRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(bloodstatusrecord.Table, bloodstatusrecord.Columns, sqlgraph.NewFieldSpec(bloodstatusrecord.FieldID, field.TypeUUID))
	_spec.From = bsrq.sql
	if unique := bsrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bsrq.path != nil {
		_spec.Unique = true
	}
	if fields := bsrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bloodstatusrecord.FieldID)
		for i := range fields {
			if fields[i] != bloodstatusrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := bsrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bsrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bsrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bsrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bsrq *BloodStatusRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bsrq.driver.Dialect())
	t1 := builder.Table(bloodstatusrecord.Table)
	columns := bsrq.ctx.Fields
	if len(columns) == 0 {
		columns = bloodstatusrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bsrq.sql != nil {
		selector = bsrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bsrq.ctx.Unique != nil && *bsrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range bsrq.predicates {
		p(selector)
	}
	for _, p := range bsrq.order {
		p(selector)
	}
	if offset := bsrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bsrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// BloodStatusRecordGroupBy is the group-by builder for BloodStatusRecord entities.
type BloodStatusRecordGroupBy struct {
	selector
	build *BloodStatusRecordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bsrgb *BloodStatusRecordGroupBy) Aggregate(fns ...AggregateFunc) *BloodStatusRecordGroupBy {
	bsrgb.fns = append(bsrgb.fns, fns...)
	return bsrgb
}

// Scan applies the selector query and scans the result into the given value.
func (bsrgb *BloodStatusRecordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bsrgb.build.ctx, ent.OpQueryGroupBy)
	if err := bsrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BloodStatusRecordQuery, *BloodStatusRecordGroupBy](ctx, bsrgb.build, bsrgb, bsrgb.build.inters, v)
}

func (bsrgb *BloodStatusRecordGroupBy) sqlScan(ctx context.Context, root *BloodStatusRecordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bsrgb.fns))
	for _, fn := range bsrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bsrgb.flds)+len(bsrgb.fns))
		for _, f := range *bsrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bsrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bsrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BloodStatusRecordSelect is the builder for selecting fields of BloodStatusRecord entities.
type BloodStatusRecordSelect struct {
	*BloodStatusRecordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bsrs *BloodStatusRecordSelect) Aggregate(fns ...AggregateFunc) *BloodStatusRecordSelect {
	bsrs.fns = append(bsrs.fns, fns...)
	return bsrs
}

// Scan applies the selector query and scans the result into the given value.
func (bsrs *BloodStatusRecordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bsrs.ctx, ent.OpQuerySelect)
	if err := bsrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BloodStatusRecordQuery, *BloodStatusRecordSelect](ctx, bsrs.BloodStatusRecordQuery, bsrs, bsrs.inters, v)
}

func (bsrs *BloodStatusRecordSelect) sqlScan(ctx context.Context, root *BloodStatusRecordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bsrs.fns))
	for _, fn := range bsrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bsrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bsrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
