// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"healthmonitor/ent/food"
	"healthmonitor/ent/predicate"
	"healthmonitor/ent/usermeal"
	"healthmonitor/ent/usermealfood"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UserMealFoodQuery is the builder for querying UserMealFood entities.
type UserMealFoodQuery struct {
	config
	ctx          *QueryContext
	order        []usermealfood.OrderOption
	inters       []Interceptor
	predicates   []predicate.UserMealFood
	withUserMeal *UserMealQuery
	withFood     *FoodQuery
	withFKs      bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserMealFoodQuery builder.
func (umfq *UserMealFoodQuery) Where(ps ...predicate.UserMealFood) *UserMealFoodQuery {
	umfq.predicates = append(umfq.predicates, ps...)
	return umfq
}

// Limit the number of records to be returned by this query.
func (umfq *UserMealFoodQuery) Limit(limit int) *UserMealFoodQuery {
	umfq.ctx.Limit = &limit
	return umfq
}

// Offset to start from.
func (umfq *UserMealFoodQuery) Offset(offset int) *UserMealFoodQuery {
	umfq.ctx.Offset = &offset
	return umfq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (umfq *UserMealFoodQuery) Unique(unique bool) *UserMealFoodQuery {
	umfq.ctx.Unique = &unique
	return umfq
}

// Order specifies how the records should be ordered.
func (umfq *UserMealFoodQuery) Order(o ...usermealfood.OrderOption) *UserMealFoodQuery {
	umfq.order = append(umfq.order, o...)
	return umfq
}

// QueryUserMeal chains the current query on the "user_meal" edge.
func (umfq *UserMealFoodQuery) QueryUserMeal() *UserMealQuery {
	query := (&UserMealClient{config: umfq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := umfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := umfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usermealfood.Table, usermealfood.FieldID, selector),
			sqlgraph.To(usermeal.Table, usermeal.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usermealfood.UserMealTable, usermealfood.UserMealColumn),
		)
		fromU = sqlgraph.SetNeighbors(umfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFood chains the current query on the "food" edge.
func (umfq *UserMealFoodQuery) QueryFood() *FoodQuery {
	query := (&FoodClient{config: umfq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := umfq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := umfq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usermealfood.Table, usermealfood.FieldID, selector),
			sqlgraph.To(food.Table, food.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, usermealfood.FoodTable, usermealfood.FoodColumn),
		)
		fromU = sqlgraph.SetNeighbors(umfq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserMealFood entity from the query.
// Returns a *NotFoundError when no UserMealFood was found.
func (umfq *UserMealFoodQuery) First(ctx context.Context) (*UserMealFood, error) {
	nodes, err := umfq.Limit(1).All(setContextOp(ctx, umfq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usermealfood.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (umfq *UserMealFoodQuery) FirstX(ctx context.Context) *UserMealFood {
	node, err := umfq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserMealFood ID from the query.
// Returns a *NotFoundError when no UserMealFood ID was found.
func (umfq *UserMealFoodQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = umfq.Limit(1).IDs(setContextOp(ctx, umfq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usermealfood.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (umfq *UserMealFoodQuery) FirstIDX(ctx context.Context) int {
	id, err := umfq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserMealFood entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserMealFood entity is found.
// Returns a *NotFoundError when no UserMealFood entities are found.
func (umfq *UserMealFoodQuery) Only(ctx context.Context) (*UserMealFood, error) {
	nodes, err := umfq.Limit(2).All(setContextOp(ctx, umfq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usermealfood.Label}
	default:
		return nil, &NotSingularError{usermealfood.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (umfq *UserMealFoodQuery) OnlyX(ctx context.Context) *UserMealFood {
	node, err := umfq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserMealFood ID in the query.
// Returns a *NotSingularError when more than one UserMealFood ID is found.
// Returns a *NotFoundError when no entities are found.
func (umfq *UserMealFoodQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = umfq.Limit(2).IDs(setContextOp(ctx, umfq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usermealfood.Label}
	default:
		err = &NotSingularError{usermealfood.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (umfq *UserMealFoodQuery) OnlyIDX(ctx context.Context) int {
	id, err := umfq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserMealFoods.
func (umfq *UserMealFoodQuery) All(ctx context.Context) ([]*UserMealFood, error) {
	ctx = setContextOp(ctx, umfq.ctx, ent.OpQueryAll)
	if err := umfq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserMealFood, *UserMealFoodQuery]()
	return withInterceptors[[]*UserMealFood](ctx, umfq, qr, umfq.inters)
}

// AllX is like All, but panics if an error occurs.
func (umfq *UserMealFoodQuery) AllX(ctx context.Context) []*UserMealFood {
	nodes, err := umfq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserMealFood IDs.
func (umfq *UserMealFoodQuery) IDs(ctx context.Context) (ids []int, err error) {
	if umfq.ctx.Unique == nil && umfq.path != nil {
		umfq.Unique(true)
	}
	ctx = setContextOp(ctx, umfq.ctx, ent.OpQueryIDs)
	if err = umfq.Select(usermealfood.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (umfq *UserMealFoodQuery) IDsX(ctx context.Context) []int {
	ids, err := umfq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (umfq *UserMealFoodQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, umfq.ctx, ent.OpQueryCount)
	if err := umfq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, umfq, querierCount[*UserMealFoodQuery](), umfq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (umfq *UserMealFoodQuery) CountX(ctx context.Context) int {
	count, err := umfq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (umfq *UserMealFoodQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, umfq.ctx, ent.OpQueryExist)
	switch _, err := umfq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (umfq *UserMealFoodQuery) ExistX(ctx context.Context) bool {
	exist, err := umfq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserMealFoodQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (umfq *UserMealFoodQuery) Clone() *UserMealFoodQuery {
	if umfq == nil {
		return nil
	}
	return &UserMealFoodQuery{
		config:       umfq.config,
		ctx:          umfq.ctx.Clone(),
		order:        append([]usermealfood.OrderOption{}, umfq.order...),
		inters:       append([]Interceptor{}, umfq.inters...),
		predicates:   append([]predicate.UserMealFood{}, umfq.predicates...),
		withUserMeal: umfq.withUserMeal.Clone(),
		withFood:     umfq.withFood.Clone(),
		// clone intermediate query.
		sql:  umfq.sql.Clone(),
		path: umfq.path,
	}
}

// WithUserMeal tells the query-builder to eager-load the nodes that are connected to
// the "user_meal" edge. The optional arguments are used to configure the query builder of the edge.
func (umfq *UserMealFoodQuery) WithUserMeal(opts ...func(*UserMealQuery)) *UserMealFoodQuery {
	query := (&UserMealClient{config: umfq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	umfq.withUserMeal = query
	return umfq
}

// WithFood tells the query-builder to eager-load the nodes that are connected to
// the "food" edge. The optional arguments are used to configure the query builder of the edge.
func (umfq *UserMealFoodQuery) WithFood(opts ...func(*FoodQuery)) *UserMealFoodQuery {
	query := (&FoodClient{config: umfq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	umfq.withFood = query
	return umfq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (umfq *UserMealFoodQuery) GroupBy(field string, fields ...string) *UserMealFoodGroupBy {
	umfq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserMealFoodGroupBy{build: umfq}
	grbuild.flds = &umfq.ctx.Fields
	grbuild.label = usermealfood.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (umfq *UserMealFoodQuery) Select(fields ...string) *UserMealFoodSelect {
	umfq.ctx.Fields = append(umfq.ctx.Fields, fields...)
	sbuild := &UserMealFoodSelect{UserMealFoodQuery: umfq}
	sbuild.label = usermealfood.Label
	sbuild.flds, sbuild.scan = &umfq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserMealFoodSelect configured with the given aggregations.
func (umfq *UserMealFoodQuery) Aggregate(fns ...AggregateFunc) *UserMealFoodSelect {
	return umfq.Select().Aggregate(fns...)
}

func (umfq *UserMealFoodQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range umfq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, umfq); err != nil {
				return err
			}
		}
	}
	for _, f := range umfq.ctx.Fields {
		if !usermealfood.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if umfq.path != nil {
		prev, err := umfq.path(ctx)
		if err != nil {
			return err
		}
		umfq.sql = prev
	}
	return nil
}

func (umfq *UserMealFoodQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserMealFood, error) {
	var (
		nodes       = []*UserMealFood{}
		withFKs     = umfq.withFKs
		_spec       = umfq.querySpec()
		loadedTypes = [2]bool{
			umfq.withUserMeal != nil,
			umfq.withFood != nil,
		}
	)
	if umfq.withUserMeal != nil || umfq.withFood != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, usermealfood.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserMealFood).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserMealFood{config: umfq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, umfq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := umfq.withUserMeal; query != nil {
		if err := umfq.loadUserMeal(ctx, query, nodes, nil,
			func(n *UserMealFood, e *UserMeal) { n.Edges.UserMeal = e }); err != nil {
			return nil, err
		}
	}
	if query := umfq.withFood; query != nil {
		if err := umfq.loadFood(ctx, query, nodes, nil,
			func(n *UserMealFood, e *Food) { n.Edges.Food = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (umfq *UserMealFoodQuery) loadUserMeal(ctx context.Context, query *UserMealQuery, nodes []*UserMealFood, init func(*UserMealFood), assign func(*UserMealFood, *UserMeal)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UserMealFood)
	for i := range nodes {
		if nodes[i].user_meal_food == nil {
			continue
		}
		fk := *nodes[i].user_meal_food
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usermeal.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_meal_food" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (umfq *UserMealFoodQuery) loadFood(ctx context.Context, query *FoodQuery, nodes []*UserMealFood, init func(*UserMealFood), assign func(*UserMealFood, *Food)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*UserMealFood)
	for i := range nodes {
		if nodes[i].food_user_meal == nil {
			continue
		}
		fk := *nodes[i].food_user_meal
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(food.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "food_user_meal" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (umfq *UserMealFoodQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := umfq.querySpec()
	_spec.Node.Columns = umfq.ctx.Fields
	if len(umfq.ctx.Fields) > 0 {
		_spec.Unique = umfq.ctx.Unique != nil && *umfq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, umfq.driver, _spec)
}

func (umfq *UserMealFoodQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usermealfood.Table, usermealfood.Columns, sqlgraph.NewFieldSpec(usermealfood.FieldID, field.TypeInt))
	_spec.From = umfq.sql
	if unique := umfq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if umfq.path != nil {
		_spec.Unique = true
	}
	if fields := umfq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usermealfood.FieldID)
		for i := range fields {
			if fields[i] != usermealfood.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := umfq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := umfq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := umfq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := umfq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (umfq *UserMealFoodQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(umfq.driver.Dialect())
	t1 := builder.Table(usermealfood.Table)
	columns := umfq.ctx.Fields
	if len(columns) == 0 {
		columns = usermealfood.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if umfq.sql != nil {
		selector = umfq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if umfq.ctx.Unique != nil && *umfq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range umfq.predicates {
		p(selector)
	}
	for _, p := range umfq.order {
		p(selector)
	}
	if offset := umfq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := umfq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserMealFoodGroupBy is the group-by builder for UserMealFood entities.
type UserMealFoodGroupBy struct {
	selector
	build *UserMealFoodQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (umfgb *UserMealFoodGroupBy) Aggregate(fns ...AggregateFunc) *UserMealFoodGroupBy {
	umfgb.fns = append(umfgb.fns, fns...)
	return umfgb
}

// Scan applies the selector query and scans the result into the given value.
func (umfgb *UserMealFoodGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, umfgb.build.ctx, ent.OpQueryGroupBy)
	if err := umfgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserMealFoodQuery, *UserMealFoodGroupBy](ctx, umfgb.build, umfgb, umfgb.build.inters, v)
}

func (umfgb *UserMealFoodGroupBy) sqlScan(ctx context.Context, root *UserMealFoodQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(umfgb.fns))
	for _, fn := range umfgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*umfgb.flds)+len(umfgb.fns))
		for _, f := range *umfgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*umfgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := umfgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserMealFoodSelect is the builder for selecting fields of UserMealFood entities.
type UserMealFoodSelect struct {
	*UserMealFoodQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (umfs *UserMealFoodSelect) Aggregate(fns ...AggregateFunc) *UserMealFoodSelect {
	umfs.fns = append(umfs.fns, fns...)
	return umfs
}

// Scan applies the selector query and scans the result into the given value.
func (umfs *UserMealFoodSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, umfs.ctx, ent.OpQuerySelect)
	if err := umfs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserMealFoodQuery, *UserMealFoodSelect](ctx, umfs.UserMealFoodQuery, umfs, umfs.inters, v)
}

func (umfs *UserMealFoodSelect) sqlScan(ctx context.Context, root *UserMealFoodQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(umfs.fns))
	for _, fn := range umfs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*umfs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := umfs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
