// Code generated by ent, DO NOT EDIT.

package adminjwtexpiredtokens

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the adminjwtexpiredtokens type in the database.
	Label = "admin_jwt_expired_tokens"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJti holds the string denoting the jti field in the database.
	FieldJti = "jti"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// Table holds the table name of the adminjwtexpiredtokens in the database.
	Table = "admin_jwt_expired_tokens"
)

// Columns holds all SQL columns for adminjwtexpiredtokens fields.
var Columns = []string{
	FieldID,
	FieldJti,
	FieldExpiresAt,
	FieldRevokedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the AdminJWTExpiredTokens queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJti orders the results by the jti field.
func ByJti(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJti, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}
