// Code generated by ent, DO NOT EDIT.

package foodnutrientsrelationships

import (
	"healthmonitor/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.FieldLTE(FieldID, id))
}

// HasFood applies the HasEdge predicate on the "food" edge.
func HasFood() predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FoodTable, FoodColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFoodWith applies the HasEdge predicate on the "food" edge with a given conditions (other predicates).
func HasFoodWith(preds ...predicate.Food) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(func(s *sql.Selector) {
		step := newFoodStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNutrient applies the HasEdge predicate on the "nutrient" edge.
func HasNutrient() predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NutrientTable, NutrientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNutrientWith applies the HasEdge predicate on the "nutrient" edge with a given conditions (other predicates).
func HasNutrientWith(preds ...predicate.Nutrient) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(func(s *sql.Selector) {
		step := newNutrientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FoodNutrientsRelationships) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FoodNutrientsRelationships) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FoodNutrientsRelationships) predicate.FoodNutrientsRelationships {
	return predicate.FoodNutrientsRelationships(sql.NotPredicates(p))
}
