// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminJWTBlacklist is the predicate function for adminjwtblacklist builders.
type AdminJWTBlacklist func(*sql.Selector)

// AdminLog is the predicate function for adminlog builders.
type AdminLog func(*sql.Selector)

// AdminMenu is the predicate function for adminmenu builders.
type AdminMenu func(*sql.Selector)

// AdminPermission is the predicate function for adminpermission builders.
type AdminPermission func(*sql.Selector)

// AdminRolePermission is the predicate function for adminrolepermission builders.
type AdminRolePermission func(*sql.Selector)

// AdminRoles is the predicate function for adminroles builders.
type AdminRoles func(*sql.Selector)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// AdminUserRole is the predicate function for adminuserrole builders.
type AdminUserRole func(*sql.Selector)
